# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
env:
  global:
matrix:
  fast_finish: true
  include:
    - name: Check code style
      python: 3.7
      env: TOXENV="run-blackcheck,run-isortcheck"
    - name: Docs
      python: 3.7
      env:
        - DOCS="true"
        # Doctr deploy key
        - secure: "GjlFTJYQnaf447j5tfQIkNgAWC0fEPvoBUFukLy0bfSnn/S21bxcLNeLNN3GDIqvZ7Ih48a+z7/+aPZ6kQPa49GysLvaTu59wkCFbbPZ9e3tDUmjvjn+EfKFASc8BjU0+bjyQCAtzuahDiqpc9qpKLh4CoVIXr/9QWSQqepWsjWcO6NI6Nx/wged0bO1bgB/LzCUwStMKs+68uyoU4cb/ApCV9BlZ9JRP8bWNDrqjRlPw+gxKxVswpVMCn3SwP3g3yrwTjVGoLlez8bguA/BkcCVagFwxvb41MMygonV2tbwTD1tHfNCO5eN00+mpxOQq3HW2o/vhjb/5xXvwB8aicd5yV0n4MyZ9mYYkcGe8WJS/p4dLs6atBsHrqJ0KzBZnhvb7f9AQEzRvDBTepv2LOxhArEcBjUd6Oqou6Gj3nijSvnSaZ1fRBCRgGgetDH9ym20zRfqv2LO3WV+s57H/mgjDafIYrORHA22X4m1Cl04Fjjgv71Del7TQBycAcNlXq9ZZw3ij059LCUL8btgHVp3g1Sl/5spPQIn7GnebcWwbT3gIScHdNL8quSdDYJBOiuRICC4ZuuurjB49TpwHrJtOs/EGQtN/xOPlbznfsdq2qBHyT7+LvfqtucoR4uICFUMz3aDP56K8vhERMvjQMw6zzw4LLEStU7N7DcNKNA="
        - BINTRAY_USER=goerz
        - BINTRAY_SUBJECT=goerz-testing
        - BINTRAY_REPO=pypkg_bintray_02
        - BINTRAY_PACKAGE=pypkg_bintray_02
        # BINTRAY_TOKEN
        - secure: IFL+OY9RrmlSUtfmDhcYJQ1eFhJuXlglSLoWTdD2smwypSzUY9u9i9Mhwpc7cT0qtzBR1UKj5LrBrzxAF8biZODc3nLQu1qjdJcae8ZqSOuO0LFWON4uHIzKkzxXWtJtmv10HpnlYObXclHNVmbmfkhjVKao2+E1aJ5UtL8Ud4SVVt1YffFFbrPTXxhyXJJqZ/3srXhBT+tIJGEbwYrTRUggXVcJ1KjSc8fdBSfYveddC4i9hZR/1mRL33nESCoGD/vFy3PyBSws1nKQdkkTxBp5Uf5bfVljFLJEbknH9kdOk+M5BvzKfz/S6h92VYL+s1bpFTVRwfFjFTloMAQCxoZWFjCOKEuxADaLhPIYziD8mJc1JGCliETyozkbs0/iJiyF5rkGj4saAHVLktabQjYRIbi/BArEkdbJ3+raOyFPI91/b6IqlCT6YjIlXMYDsjP1/qBJo+LU/RLKxEl++h9NlLyp0sxxBV8lF7Y+TC3k+F77iUKaDncLH0boFql4odEvAC1tcrl6iBs6r9isQiOiIkKXUf4FH/CNZzrD9NQqlzeLNFmgXl210FttL1O1MZbB0fzEFvqNl7z1S20eRWGSvb2Sf3GeJJMPOM1NwYHkoICcotW/lbifiC6sXX4RWm4Z3dKvnqVkUZmqGDkAPqepDIos87dX0aY8DVZXSFs=
      addons:
        apt_packages:
    - name: Python 3.6
      python: 3.6
      env: TOXENV=py36-test
    - name: Python 3.7
      python: 3.7
      env: TOXENV=py37-test
    - name: Python 3.8
      python: 3.8
      env: TOXENV=py38-test

install:
  # any failure stops the build
  - set -e
  - pip install tox zip-files
  - pip freeze
  - printenv
script:
  # any failure stops testing immediately
  - set -e
  - |
    if [[ "${DOCS}" == "true" ]]; then
      source .travis/doctr_build.sh
    else
      tox -e $TOXENV
    fi
  - echo "DONE"
after_success:
  - if [[ "${TOXENV}" =~ test ]]; then tox -e $(echo "${TOXENV}" | sed s/test/runcmd/) -- codecov; fi
